#!/usr/bin/env php
<?php

include_once __DIR__ . "/core/Console.php";

switch ($argv[1]){

    case "sayHello" :
        Console::sayHello();
        break;

    default :
        Console::info();
        break;
}
